version=${project.version}
buildtime=${timestamp}
builder=${env.USERNAME}
builderName=${election.build.user.name}
builderEmail=${election.build.user.email}
buildhost=${env.COMPUTERNAME}
buildOs=${os.name}
gitBranch=${election.branch}
gitCommitIdDescribe=${election.commit.id.describe}
gitCommitId=${election.commit.id.full}
gitCommitUrl=${election.remote.origin.url}
gitCommitTime=${election.commit.time}
gitDirty=${election.dirty}